spring:
  application:
    name: notification-service
  config:
    import: optional:classpath:secrets.properties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notificationService
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://127.0.0.1:8086
        specific.avro.reader: true
    listener:
      observation-enabled: true
    template:
      observation-enabled: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${mail.username}
    password: ${mail.password}
  jackson:
    deserialization:
      fail-on-unknown-properties: false

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}

server:
  port: 8085