spring:
  application:
    name: api-gateway

  config:
    import: optional:classpath:secrets.properties

  mvc:
    hiddenmethod:
      filter:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: api-gateway-instance
    prefer-ip-address: true

jwt:
  secret: ${jwt.secret}

server:
  port: 8080
