spring:
  application:
    name: api-gateway
  mvc:
    hiddenmethod:
      filter:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: api-gateway-instance
    prefer-ip-address: true

jwt:
  secret: 4b6050b9a135b722dab15dabc4f22d246b705030ec5af354221550b89c735ed8

server:
  port: 8080
