---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  db-host: "postgres"
  db-port: "5432"

  kafka-bootstrap-servers: "kafka:9092"
  kafka-properties-schema-registry-url: "http://schema-registry:8081"

  redis-host: "redis-master"
  redis-port: "6379"

  spring-datasource-hikari-pool-name: "HikariPool-1"

  otlp-tracing-endpoint: "http://tempo.observability.svc.cluster.local:4318/v1/traces"