---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  db-username: "changeme"
  db-password: "changeme"
  jwt-secret: "changeme"
  mail-username: "changeme"
  mail-password: "changeme"