/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.reviewservice.event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RatingUpdatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 683640969396120354L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RatingUpdatedEvent\",\"namespace\":\"com.example.reviewservice.event\",\"fields\":[{\"name\":\"propertyId\",\"type\":\"long\"},{\"name\":\"newAverageRating\",\"type\":\"double\"},{\"name\":\"totalReviews\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RatingUpdatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RatingUpdatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RatingUpdatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RatingUpdatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RatingUpdatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RatingUpdatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RatingUpdatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RatingUpdatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RatingUpdatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long propertyId;
  private double newAverageRating;
  private long totalReviews;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RatingUpdatedEvent() {}

  /**
   * All-args constructor.
   * @param propertyId The new value for propertyId
   * @param newAverageRating The new value for newAverageRating
   * @param totalReviews The new value for totalReviews
   */
  public RatingUpdatedEvent(java.lang.Long propertyId, java.lang.Double newAverageRating, java.lang.Long totalReviews) {
    this.propertyId = propertyId;
    this.newAverageRating = newAverageRating;
    this.totalReviews = totalReviews;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return propertyId;
    case 1: return newAverageRating;
    case 2: return totalReviews;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: propertyId = (java.lang.Long)value$; break;
    case 1: newAverageRating = (java.lang.Double)value$; break;
    case 2: totalReviews = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'propertyId' field.
   * @return The value of the 'propertyId' field.
   */
  public long getPropertyId() {
    return propertyId;
  }


  /**
   * Sets the value of the 'propertyId' field.
   * @param value the value to set.
   */
  public void setPropertyId(long value) {
    this.propertyId = value;
  }

  /**
   * Gets the value of the 'newAverageRating' field.
   * @return The value of the 'newAverageRating' field.
   */
  public double getNewAverageRating() {
    return newAverageRating;
  }


  /**
   * Sets the value of the 'newAverageRating' field.
   * @param value the value to set.
   */
  public void setNewAverageRating(double value) {
    this.newAverageRating = value;
  }

  /**
   * Gets the value of the 'totalReviews' field.
   * @return The value of the 'totalReviews' field.
   */
  public long getTotalReviews() {
    return totalReviews;
  }


  /**
   * Sets the value of the 'totalReviews' field.
   * @param value the value to set.
   */
  public void setTotalReviews(long value) {
    this.totalReviews = value;
  }

  /**
   * Creates a new RatingUpdatedEvent RecordBuilder.
   * @return A new RatingUpdatedEvent RecordBuilder
   */
  public static com.example.reviewservice.event.RatingUpdatedEvent.Builder newBuilder() {
    return new com.example.reviewservice.event.RatingUpdatedEvent.Builder();
  }

  /**
   * Creates a new RatingUpdatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RatingUpdatedEvent RecordBuilder
   */
  public static com.example.reviewservice.event.RatingUpdatedEvent.Builder newBuilder(com.example.reviewservice.event.RatingUpdatedEvent.Builder other) {
    if (other == null) {
      return new com.example.reviewservice.event.RatingUpdatedEvent.Builder();
    } else {
      return new com.example.reviewservice.event.RatingUpdatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new RatingUpdatedEvent RecordBuilder by copying an existing RatingUpdatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new RatingUpdatedEvent RecordBuilder
   */
  public static com.example.reviewservice.event.RatingUpdatedEvent.Builder newBuilder(com.example.reviewservice.event.RatingUpdatedEvent other) {
    if (other == null) {
      return new com.example.reviewservice.event.RatingUpdatedEvent.Builder();
    } else {
      return new com.example.reviewservice.event.RatingUpdatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for RatingUpdatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RatingUpdatedEvent>
    implements org.apache.avro.data.RecordBuilder<RatingUpdatedEvent> {

    private long propertyId;
    private double newAverageRating;
    private long totalReviews;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.reviewservice.event.RatingUpdatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.propertyId)) {
        this.propertyId = data().deepCopy(fields()[0].schema(), other.propertyId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.newAverageRating)) {
        this.newAverageRating = data().deepCopy(fields()[1].schema(), other.newAverageRating);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.totalReviews)) {
        this.totalReviews = data().deepCopy(fields()[2].schema(), other.totalReviews);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing RatingUpdatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.reviewservice.event.RatingUpdatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.propertyId)) {
        this.propertyId = data().deepCopy(fields()[0].schema(), other.propertyId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.newAverageRating)) {
        this.newAverageRating = data().deepCopy(fields()[1].schema(), other.newAverageRating);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.totalReviews)) {
        this.totalReviews = data().deepCopy(fields()[2].schema(), other.totalReviews);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'propertyId' field.
      * @return The value.
      */
    public long getPropertyId() {
      return propertyId;
    }


    /**
      * Sets the value of the 'propertyId' field.
      * @param value The value of 'propertyId'.
      * @return This builder.
      */
    public com.example.reviewservice.event.RatingUpdatedEvent.Builder setPropertyId(long value) {
      validate(fields()[0], value);
      this.propertyId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'propertyId' field has been set.
      * @return True if the 'propertyId' field has been set, false otherwise.
      */
    public boolean hasPropertyId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'propertyId' field.
      * @return This builder.
      */
    public com.example.reviewservice.event.RatingUpdatedEvent.Builder clearPropertyId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'newAverageRating' field.
      * @return The value.
      */
    public double getNewAverageRating() {
      return newAverageRating;
    }


    /**
      * Sets the value of the 'newAverageRating' field.
      * @param value The value of 'newAverageRating'.
      * @return This builder.
      */
    public com.example.reviewservice.event.RatingUpdatedEvent.Builder setNewAverageRating(double value) {
      validate(fields()[1], value);
      this.newAverageRating = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'newAverageRating' field has been set.
      * @return True if the 'newAverageRating' field has been set, false otherwise.
      */
    public boolean hasNewAverageRating() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'newAverageRating' field.
      * @return This builder.
      */
    public com.example.reviewservice.event.RatingUpdatedEvent.Builder clearNewAverageRating() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalReviews' field.
      * @return The value.
      */
    public long getTotalReviews() {
      return totalReviews;
    }


    /**
      * Sets the value of the 'totalReviews' field.
      * @param value The value of 'totalReviews'.
      * @return This builder.
      */
    public com.example.reviewservice.event.RatingUpdatedEvent.Builder setTotalReviews(long value) {
      validate(fields()[2], value);
      this.totalReviews = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'totalReviews' field has been set.
      * @return True if the 'totalReviews' field has been set, false otherwise.
      */
    public boolean hasTotalReviews() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'totalReviews' field.
      * @return This builder.
      */
    public com.example.reviewservice.event.RatingUpdatedEvent.Builder clearTotalReviews() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RatingUpdatedEvent build() {
      try {
        RatingUpdatedEvent record = new RatingUpdatedEvent();
        record.propertyId = fieldSetFlags()[0] ? this.propertyId : (java.lang.Long) defaultValue(fields()[0]);
        record.newAverageRating = fieldSetFlags()[1] ? this.newAverageRating : (java.lang.Double) defaultValue(fields()[1]);
        record.totalReviews = fieldSetFlags()[2] ? this.totalReviews : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RatingUpdatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<RatingUpdatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RatingUpdatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<RatingUpdatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.propertyId);

    out.writeDouble(this.newAverageRating);

    out.writeLong(this.totalReviews);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.propertyId = in.readLong();

      this.newAverageRating = in.readDouble();

      this.totalReviews = in.readLong();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.propertyId = in.readLong();
          break;

        case 1:
          this.newAverageRating = in.readDouble();
          break;

        case 2:
          this.totalReviews = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










